create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.content_items (
  id text primary key default gen_random_uuid()::text,
  type text not null check (type in ('video', 'event', 'course', 'tool')),
  title text not null check (char_length(title) between 1 and 180),
  description text not null check (char_length(description) between 1 and 12000),
  category text,
  url text,
  image_url text,
  event_date date,
  label text,
  featured boolean not null default false,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.traffic_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'outbound_click')),
  page_path text not null check (char_length(page_path) between 1 and 500),
  destination_url text check (destination_url is null or char_length(destination_url) <= 1500),
  referrer text check (referrer is null or char_length(referrer) <= 1500),
  session_id text not null check (char_length(session_id) between 1 and 100),
  occurred_at timestamptz not null default now()
);

create index if not exists idx_content_items_type_published
  on public.content_items(type, published, created_at desc);

create index if not exists idx_traffic_events_occurred_at
  on public.traffic_events(occurred_at desc);

create index if not exists idx_traffic_events_type_occurred_at
  on public.traffic_events(event_type, occurred_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists content_items_set_updated_at on public.content_items;
create trigger content_items_set_updated_at
before update on public.content_items
for each row execute function public.set_updated_at();

alter table public.admin_users enable row level security;
alter table public.content_items enable row level security;
alter table public.traffic_events enable row level security;

grant select on public.admin_users to authenticated;
grant select on public.content_items to anon, authenticated;
grant insert, update, delete on public.content_items to authenticated;
grant insert on public.traffic_events to anon, authenticated;
grant select on public.traffic_events to authenticated;
grant usage, select on sequence public.traffic_events_id_seq to anon, authenticated;

drop policy if exists "Admins can read their access" on public.admin_users;
create policy "Admins can read their access"
on public.admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Published content is public" on public.content_items;
create policy "Published content is public"
on public.content_items for select
to anon, authenticated
using (published);

drop policy if exists "Admins can read all content" on public.content_items;
create policy "Admins can read all content"
on public.content_items for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can create content" on public.content_items;
create policy "Admins can create content"
on public.content_items for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update content" on public.content_items;
create policy "Admins can update content"
on public.content_items for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete content" on public.content_items;
create policy "Admins can delete content"
on public.content_items for delete
to authenticated
using (public.is_admin());

drop policy if exists "Visitors can record traffic" on public.traffic_events;
create policy "Visitors can record traffic"
on public.traffic_events for insert
to anon, authenticated
with check (
  event_type in ('page_view', 'outbound_click')
  and char_length(page_path) between 1 and 500
  and char_length(session_id) between 1 and 100
);

drop policy if exists "Admins can read traffic" on public.traffic_events;
create policy "Admins can read traffic"
on public.traffic_events for select
to authenticated
using (public.is_admin());

insert into public.admin_users (user_id)
select id
from auth.users
where lower(email) = 'theadrian7@gmail.com'
on conflict (user_id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'content-images',
  'content-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public content images are readable" on storage.objects;
create policy "Public content images are readable"
on storage.objects for select
to public
using (bucket_id = 'content-images');

drop policy if exists "Admins can upload content images" on storage.objects;
create policy "Admins can upload content images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'content-images' and public.is_admin());

drop policy if exists "Admins can update content images" on storage.objects;
create policy "Admins can update content images"
on storage.objects for update
to authenticated
using (bucket_id = 'content-images' and public.is_admin())
with check (bucket_id = 'content-images' and public.is_admin());

drop policy if exists "Admins can delete content images" on storage.objects;
create policy "Admins can delete content images"
on storage.objects for delete
to authenticated
using (bucket_id = 'content-images' and public.is_admin());

insert into public.content_items
  (id, type, title, description, category, url, image_url, event_date, label, featured, published, created_at)
values
  ('event-elshinta', 'event', 'AIGrowth x Elshinta Radio', 'Talkshow radio tentang penerapan AI untuk bisnis dan kreator.', 'Radio Talkshow', null, '/elshinta.jpg', null, null, false, true, '2026-01-01T00:00:00Z'),
  ('event-smesco', 'event', 'AIGrowth x Smesco', 'Webinar AI praktis untuk membantu UMKM bertumbuh.', 'Webinar UMKM', null, '/smesco.png', null, null, false, true, '2026-01-02T00:00:00Z'),
  ('event-cekat-ai', 'event', 'AIGrowth x Cekat AI', 'Kolaborasi komunitas dalam konferensi dan diskusi teknologi AI.', 'Tech Conference', null, '/cekatai.jpg', null, null, false, true, '2026-01-03T00:00:00Z'),
  ('event-om-botak', 'event', 'AIGrowth x Om Botak', 'Workshop langsung untuk membangun workflow AI yang praktis.', 'Workshop', null, '/ombotak.jpg', null, null, false, true, '2026-01-04T00:00:00Z'),
  ('event-shenzhen', 'event', 'AI Tech Trip - Shenzhen', 'Kunjungan teknologi untuk melihat perkembangan AI secara langsung.', 'International', null, '/china1.jpg', null, null, false, true, '2026-01-05T00:00:00Z'),
  ('event-robotics', 'event', 'Exploring Future Tech', 'Eksplorasi robotika dan teknologi masa depan bersama komunitas.', 'Robotics', null, '/china2.jpg', null, null, false, true, '2026-01-06T00:00:00Z'),
  ('course-open-claw', 'course', 'Open Claw Course', 'Kelas praktis dari AIGrowth untuk membantu Anda menerapkan AI ke dalam alur kerja profesional secara terarah.', 'Online Course', 'https://s.id/openclawadr', null, null, 'Lihat Detail Course', true, true, '2026-01-07T00:00:00Z'),
  ('tool-dibales', 'tool', 'Dibales.ai', 'Platform AI untuk otomasi media sosial yang membantu membalas komentar dan pesan pelanggan secara lebih cepat.', 'Social Media', 'https://s.id/dibalesai', null, null, 'Lihat Detail', true, true, '2026-01-08T00:00:00Z'),
  ('video-ai-agent-sosmed', 'video', 'AI Agent Untuk Sosmed: Otomatisasi Konten dari Riset sampai Posting', 'Pelajari workflow AI Agent untuk riset, produksi, dan distribusi konten media sosial secara lebih efisien.', 'AI Automation', 'https://www.youtube.com/watch?v=vSC5kW4us04', null, null, null, false, true, '2026-01-09T00:00:00Z'),
  ('video-chatgpt-pemula', 'video', 'Cara Cari Uang Pakai ChatGPT untuk Pemula', 'Panduan praktis memulai layanan berbasis ChatGPT dengan modal terjangkau dan langkah yang mudah diikuti.', 'ChatGPT', 'https://www.youtube.com/watch?v=rHVyU4-cht0', null, null, null, false, true, '2026-01-10T00:00:00Z')
on conflict (id) do nothing;
